### PR TITLE
Product namespace

### PR DESCRIPTION
**Pull request by adeebahmed**
Expanded upon the work that @silasdavis started here: https://github.com/hyperledger/grid/pull/125

Closes https://jira.hyperledger.org/browse/GRID-97

This PR also adds a makefile at the top level to quickly run cargo commands across all subdirectories. 
```
make build_all   - (runs cargo build in all the subdirectories with a Cargo.toml)
make test_all   - (runs cargo test in all the subdirectories with a Cargo.toml)
make clip_all   - (runs cargo clippy in all the subdirectories with a Cargo.toml)
make fmt_all   - (runs cargo fmt in all the subdirectories with a Cargo.toml)
```

The Makefile may solve the intent of: https://jira.hyperledger.org/browse/GRID-31

### CODE REVIEW

**Comment by silasdavis** [comment]
ah perf :)

**Comment by rbuysse** [comment]
I just opened PR#127 which adds a top-level workspace Cargo.toml which will close Jira 31 and feels like the rustier way to do things.

Can you take a look and close this one if PR#127 meets your needs?

**Comment by dcmiddle** [comment]
@adeebahmed please see Ryan's question ^

**Comment by adeebahmed** [comment]
lgtm

**Pull request closed without merging**
